/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wolfieball_draft_kit;

/**
 *
 * @author shilinlu
 */
public enum PropertyType {
    // LOADED FROM properties.xml
        PROP_APP_TITLE,
        
        // APPLICATION ICONS
        NEW_DRAFT_ICON,
        LOAD_DRAFT_ICON,
        SAVE_DRAFT_ICON,
        VIEW_DRAFT_ICON,
        EXPORT_DRAFT_ICON,
        DELETE_ICON,
        EXIT_ICON,
        AVAILABLE_PLAYERS_ICON,
        DRAFT_SUMMARY_ICON,
        FANTASY_STANDING_ICON,
        FANTASY_TEAMS_ICON,
        MLB_TEAM_ICON,
        ADD_ICON,
        MINUS_ICON,
        EDIT_TEAM_ICON,
        STAR_ICON,
        PLAY_ICON,
        PAUSE_ICON,
        // APPLICATION TOOLTIPS FOR BUTTONS
        NEW_DRAFT_TOOLTIP,
        LOAD_DRAFT_TOOLTIP,
        SAVE_DRAFT_TOOLTIP,
        VIEW_DRAFT_TOOLTIP,
        EXPORT_DRAFT_TOOLTIP,
        STAR_TOOLTIP,
        START_TOOLTIP,
        PAUSE_TOOLTIP,
        AVAILABLE_PLAYERS_TOOLTIP,
        DRAFT_SUMMARY_TOOLTIP,
        FANTASY_STANDING_TOOLTIP,
        FANTASY_TEAMS_TOOLTIP,
        MLB_TEAM_TOOLTIP,
        REMOVE_TEAM_TOOLTIP,
        ADD_TEAM_TOOLTIP,
        DELETE_TOOLTIP,
        EXIT_TOOLTIP,
        ADD_ITEM_TOOLTIP,
        REMOVE_ITEM_TOOLTIP,
        ADD_LECTURE_TOOLTIP,
        REMOVE_LECTURE_TOOLTIP,
        MOVE_UP_LECTURE_TOOLTIP,
        MOVE_DOWN_LECTURE_TOOLTIP,
        ADD_HW_TOOLTIP,
        REMOVE_HW_TOOLTIP,        
        EDIT_TEAM_TOOLTIP,
        // FOR COURSE EDIT WORKSPACE
        TAXI_SQUAD_LABEL,
        STARTING_LINEUP_LABEL,
        FANTASY_TEAMS_LABEL,
        FANTASY_STANDINGS_LABEL,
        AVAILABLE_PLAYERS_LABEL,
        DRAFT_SUMMARY_LABEL,
        MLB_TEAMS_LABEL,
        SEARCH_LABEL,
        DRAFT_NAME_LABEL,
        COURSE_TITLE_LABEL,
        INSTRUCTOR_NAME_LABEL,
        INSTRUCTOR_URL_LABEL,
        PAGES_SELECTION_HEADING_LABEL,
        SCHEDULE_ITEMS_HEADING_LABEL,
        LECTURES_HEADING_LABEL,
        HWS_HEADING_LABEL,
        SELECT_FANTASY_TEAM_LABEL,
        // PAGE CHECKBOX LABELS
        INDEX_CHECKBOX_LABEL,
        SYLLABUS_CHECKBOX_LABEL,
        SCHEDULE_CHECKBOX_LABEL,
        HWS_CHECKBOX_LABEL,
        PROJECTS_CHECKBOX_LABEL,
        SELECT_PRO_TEAM_LABEL,        
        // FOR SCHEDULE EDITING
        SCHEDULE_HEADING_LABEL,
        DATE_BOUNDARIES_LABEL,
        STARTING_MONDAY_LABEL,
        ENDING_FRIDAY_LABEL,
        LECTURE_DAY_SELECT_LABEL,
        
        // ERROR DIALOG MESSAGES
        START_DATE_AFTER_END_DATE_ERROR_MESSAGE,
        START_DATE_NOT_A_MONDAY_ERROR_MESSAGE,
        END_DATE_NOT_A_FRIDAY_ERROR_MESSAGE,
        ILLEGAL_DATE_MESSAGE,
        
        // AND VERIFICATION MESSAGES
        NEW_DRAFT_CREATED_MESSAGE,
        DRAFT_LOADED_MESSAGE,
        DRAFT_SAVED_MESSAGE,
        SITE_EXPORTED_MESSAGE,
        SAVE_UNSAVED_WORK_MESSAGE,
        REMOVE_ITEM_MESSAGE


}
